name: Package Version Tags
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: butr/actions-common-setup@v1.2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
      
    - name: Pack
      run: dotnet pack -c Release --no-build --include-symbols
      
    - name: Push Nupkg to GitHub Packages
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
        nupkg-path: './FetchBannerlordVersion/nupkg/*.nupkg'
        repo-owner: 'BUTR'
        gh-user: 'Tyler-IN'
        token: ${{ secrets.GITHUB_TOKEN }}
